from pathlib import Path


APP_NAME = "Access WeChat Article"
PROJECT_ROOT = Path(__file__).resolve().parents[3]
WEBVIEW_DIR = PROJECT_ROOT / "src" / "webview"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 675
WINDOW_MIN_WIDTH = 960
WINDOW_MIN_HEIGHT = 540
WINDOW_MIN_SIZE = (WINDOW_MIN_WIDTH, WINDOW_MIN_HEIGHT)
WINDOW_ASPECT_RATIO = WINDOW_WIDTH / WINDOW_HEIGHT
